import java.util.*;

class Solution {
    public int[] findOrder(int numCourses, int[][] prerequisites) {
            int[] inDegree = new int[numCourses];
                    List<List<Integer>> adj = new ArrayList<>();
                            
                                    for (int i = 0; i < numCourses; i++) {
                                                adj.add(new ArrayList<>());
                                                        }
                                                                
                                                                        // Build the graph: [a, b] means b -> a (b is a prerequisite for a)
                                                                                for (int[] pre : prerequisites) {
                                                                                            int course = pre[0];
                                                                                                        int prerequisite = pre[1];
                                                                                                                    adj.get(prerequisite).add(course);
                                                                                                                                inDegree[course]++;
                                                                                                                                        }
                                                                                                                                                
                                                                                                                                                        Queue<Integer> queue = new LinkedList<>();
                                                                                                                                                                for (int i = 0; i < numCourses; i++) {
                                                                                                                                                                            if (inDegree[i] == 0) {
                                                                                                                                                                                            queue.offer(i);
                                                                                                                                                                                                        }
                                                                                                                                                                                                                }
                                                                                                                                                                                                                        
                                                                                                                                                                                                                                int[] result = new int[numCourses];
                                                                                                                                                                                                                                        int index = 0;
                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                        while (!queue.isEmpty()) {
                                                                                                                                                                                                                                                                    int current = queue.poll();
                                                                                                                                                                                                                                                                                result[index++] = current; // Add the course to our order
                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                        for (int neighbor : adj.get(current)) {
                                                                                                                                                                                                                                                                                                                        inDegree[neighbor]--;
                                                                                                                                                                                                                                                                                                                                        if (inDegree[neighbor] == 0) {
                                                                                                                                                                                                                                                                                                                                                            queue.offer(neighbor);
                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                // If index isn't equal to numCourses, we found a cycle
                                                                                                                                                                                                                                                                                                                                                                                                                        return (index == numCourses) ? result : new int[0];
                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                            }