import java.util.*;

class Solution {
    public int[] sortItems(int n, int m, int[] group, List<List<Integer>> beforeItems) {
            // 1. Assign unique group IDs to items belonging to no group (-1)
                    int groupId = m;
                            for (int i = 0; i < n; i++) {
                                        if (group[i] == -1) {
                                                        group[i] = groupId++;
                                                                    }
                                                                            }

                                                                                    // 2. Initialize graphs and in-degree arrays
                                                                                            List<List<Integer>> itemAdj = new ArrayList<>();
                                                                                                    List<List<Integer>> groupAdj = new ArrayList<>();
                                                                                                            for (int i = 0; i < n; i++) itemAdj.add(new ArrayList<>());
                                                                                                                    for (int i = 0; i < groupId; i++) groupAdj.add(new ArrayList<>());

                                                                                                                            int[] itemInDegree = new int[n];
                                                                                                                                    int[] groupInDegree = new int[groupId];

                                                                                                                                            // 3. Build the graphs
                                                                                                                                                    for (int i = 0; i < n; i++) {
                                                                                                                                                                int toGroup = group[i];
                                                                                                                                                                            for (int before : beforeItems.get(i)) {
                                                                                                                                                                                            int fromGroup = group[before];
                                                                                                                                                                                                            
                                                                                                                                                                                                                            // Item dependency
                                                                                                                                                                                                                                            itemAdj.get(before).add(i);
                                                                                                                                                                                                                                                            itemInDegree[i]++;

                                                                                                                                                                                                                                                                            // Group dependency (only if they are in different groups)
                                                                                                                                                                                                                                                                                            if (fromGroup != toGroup) {
                                                                                                                                                                                                                                                                                                                groupAdj.get(fromGroup).add(toGroup);
                                                                                                                                                                                                                                                                                                                                    groupInDegree[toGroup]++;
                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                // 4. Topological Sort for both Items and Groups
                                                                                                                                                                                                                                                                                                                                                                                        List<Integer> itemOrder = topologicalSort(itemAdj, itemInDegree, n);
                                                                                                                                                                                                                                                                                                                                                                                                List<Integer> groupOrder = topologicalSort(groupAdj, groupInDegree, groupId);

                                                                                                                                                                                                                                                                                                                                                                                                        if (itemOrder.isEmpty() || groupOrder.isEmpty()) {
                                                                                                                                                                                                                                                                                                                                                                                                                    return new int[0];
                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                    // 5. Group items together based on their group ID
                                                                                                                                                                                                                                                                                                                                                                                                                                            Map<Integer, List<Integer>> groupToItems = new HashMap<>();
                                                                                                                                                                                                                                                                                                                                                                                                                                                    for (int item : itemOrder) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                int g = group[item];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            groupToItems.computeIfAbsent(g, k -> new ArrayList<>()).add(item);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // 6. Concatenate items in the order of the sorted groups
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    int[] result = new int[n];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            int idx = 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    for (int g : groupOrder) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                List<Integer> items = groupToItems.getOrDefault(g, new ArrayList<>());
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            for (int item : items) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            result[idx++] = item;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return result;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                private List<Integer> topologicalSort(List<List<Integer>> adj, int[] inDegree, int count) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        List<Integer> order = new ArrayList<>();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Queue<Integer> queue = new LinkedList<>();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        for (int i = 0; i < inDegree.length; i++) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (inDegree[i] == 0) queue.offer(i);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    while (!queue.isEmpty()) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                int curr = queue.poll();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            order.add(curr);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        for (int neighbor : adj.get(curr)) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        inDegree[neighbor]--;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (inDegree[neighbor] == 0) queue.offer(neighbor);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return order.size() == count ? order : new ArrayList<>();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }