import java.util.*;

class Solution {
    public int[] shortestAlternatingPaths(int n, int[][] redEdges, int[][] blueEdges) {
            // Build adjacency lists for both colors
                    List<Integer>[] redAdj = new ArrayList[n];
                            List<Integer>[] blueAdj = new ArrayList[n];
                                    for (int i = 0; i < n; i++) {
                                                redAdj[i] = new ArrayList<>();
                                                            blueAdj[i] = new ArrayList<>();
                                                                    }
                                                                            for (int[] edge : redEdges) redAdj[edge[0]].add(edge[1]);
                                                                                    for (int[] edge : blueEdges) blueAdj[edge[0]].add(edge[1]);

                                                                                            int[] res = new int[n];
                                                                                                    Arrays.fill(res, -1);
                                                                                                            
                                                                                                                    // visited[node][color]: 0 for red, 1 for blue
                                                                                                                            boolean[][] visited = new boolean[n][2];
                                                                                                                                    
                                                                                                                                            // Queue stores: {node, current_distance, color_of_incoming_edge}
                                                                                                                                                    // color: 0 for Red, 1 for Blue
                                                                                                                                                            Queue<int[]> queue = new LinkedList<>();
                                                                                                                                                                    
                                                                                                                                                                            // Start at node 0. We can "arrive" via either color initially.
                                                                                                                                                                                    queue.offer(new int[]{0, 0, 0}); // Imagine arrived at 0 via Red
                                                                                                                                                                                            queue.offer(new int[]{0, 0, 1}); // Imagine arrived at 0 via Blue
                                                                                                                                                                                                    visited[0][0] = true;
                                                                                                                                                                                                            visited[0][1] = true;
                                                                                                                                                                                                                    res[0] = 0;

                                                                                                                                                                                                                            while (!queue.isEmpty()) {
                                                                                                                                                                                                                                        int[] curr = queue.poll();
                                                                                                                                                                                                                                                    int node = curr[0];
                                                                                                                                                                                                                                                                int dist = curr[1];
                                                                                                                                                                                                                                                                            int color = curr[2];

                                                                                                                                                                                                                                                                                        // If we arrived via Red (0), we must now use a Blue (1) edge
                                                                                                                                                                                                                                                                                                    List<Integer>[] nextAdj = (color == 0) ? blueAdj : redAdj;
                                                                                                                                                                                                                                                                                                                int nextColor = 1 - color;

                                                                                                                                                                                                                                                                                                                            for (int neighbor : nextAdj[node]) {
                                                                                                                                                                                                                                                                                                                                            if (!visited[neighbor][nextColor]) {
                                                                                                                                                                                                                                                                                                                                                                visited[neighbor][nextColor] = true;
                                                                                                                                                                                                                                                                                                                                                                                    queue.offer(new int[]{neighbor, dist + 1, nextColor});
                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                            // If this is the first time we've reached this node (shortest path)
                                                                                                                                                                                                                                                                                                                                                                                                                                                if (res[neighbor] == -1) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        res[neighbor] = dist + 1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return res;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }