import java.util.*;

class Solution {
    public List<List<String>> accountsMerge(List<List<String>> accounts) {
            DSU dsu = new DSU(10001); // Constraint: max emails roughly 1000 accounts * 10 emails
                    Map<String, String> emailToName = new HashMap<>();
                            Map<String, Integer> emailToId = new HashMap<>();
                                    int id = 0;

                                            for (List<String> account : accounts) {
                                                        String name = account.get(0);
                                                                    for (int i = 1; i < account.size(); i++) {
                                                                                    String email = account.get(i);
                                                                                                    if (!emailToId.containsKey(email)) {
                                                                                                                        emailToId.put(email, id++);
                                                                                                                                        }
                                                                                                                                                        emailToName.put(email, name);
                                                                                                                                                                        // Union the first email of the account with the rest
                                                                                                                                                                                        dsu.union(emailToId.get(account.get(1)), emailToId.get(email));
                                                                                                                                                                                                    }
                                                                                                                                                                                                            }

                                                                                                                                                                                                                    // Group emails by their root parent ID
                                                                                                                                                                                                                            Map<Integer, List<String>> ans = new HashMap<>();
                                                                                                                                                                                                                                    for (String email : emailToId.keySet()) {
                                                                                                                                                                                                                                                int root = dsu.find(emailToId.get(email));
                                                                                                                                                                                                                                                            ans.computeIfAbsent(root, x -> new ArrayList<>()).add(email);
                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                            // Format the final result
                                                                                                                                                                                                                                                                                    List<List<String>> res = new ArrayList<>();
                                                                                                                                                                                                                                                                                            for (List<String> component : ans.values()) {
                                                                                                                                                                                                                                                                                                        Collections.sort(component);
                                                                                                                                                                                                                                                                                                                    List<String> mergedAccount = new ArrayList<>();
                                                                                                                                                                                                                                                                                                                                mergedAccount.add(emailToName.get(component.get(0)));
                                                                                                                                                                                                                                                                                                                                            mergedAccount.addAll(component);
                                                                                                                                                                                                                                                                                                                                                        res.add(mergedAccount);
                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                        return res;
                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                            class DSU {
                                                                                                                                                                                                                                                                                                                                                                                int[] parent;
                                                                                                                                                                                                                                                                                                                                                                                    public DSU(int sz) {
                                                                                                                                                                                                                                                                                                                                                                                            parent = new int[sz];
                                                                                                                                                                                                                                                                                                                                                                                                    for (int i = 0; i < sz; ++i) parent[i] = i;
                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                            public int find(int x) {
                                                                                                                                                                                                                                                                                                                                                                                                                    if (parent[x] != x) parent[x] = find(parent[x]);
                                                                                                                                                                                                                                                                                                                                                                                                                            return parent[x];
                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                    public void union(int x, int y) {
                                                                                                                                                                                                                                                                                                                                                                                                                                            parent[find(x)] = find(y);
                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                }