import java.util.*;

class Solution {
    public boolean canFinish(int numCourses, int[][] prerequisites) {
            int[] inDegree = new int[numCourses];
                    List<List<Integer>> adj = new ArrayList<>();
                            
                                    for (int i = 0; i < numCourses; i++) {
                                                adj.add(new ArrayList<>());
                                                        }
                                                                
                                                                        // Build the graph: [a, b] means b -> a (b is a prerequisite for a)
                                                                                for (int[] pre : prerequisites) {
                                                                                            int course = pre[0];
                                                                                                        int prerequisite = pre[1];
                                                                                                                    adj.get(prerequisite).add(course);
                                                                                                                                inDegree[course]++;
                                                                                                                                        }
                                                                                                                                                
                                                                                                                                                        // Queue for BFS: starts with courses having 0 prerequisites
                                                                                                                                                                Queue<Integer> queue = new LinkedList<>();
                                                                                                                                                                        for (int i = 0; i < numCourses; i++) {
                                                                                                                                                                                    if (inDegree[i] == 0) {
                                                                                                                                                                                                    queue.offer(i);
                                                                                                                                                                                                                }
                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                
                                                                                                                                                                                                                                        int count = 0;
                                                                                                                                                                                                                                                while (!queue.isEmpty()) {
                                                                                                                                                                                                                                                            int current = queue.poll();
                                                                                                                                                                                                                                                                        count++;
                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                for (int neighbor : adj.get(current)) {
                                                                                                                                                                                                                                                                                                                inDegree[neighbor]--;
                                                                                                                                                                                                                                                                                                                                if (inDegree[neighbor] == 0) {
                                                                                                                                                                                                                                                                                                                                                    queue.offer(neighbor);
                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                        // If we processed all courses, no cycle exists
                                                                                                                                                                                                                                                                                                                                                                                                                return count == numCourses;
                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                    }