class Solution {
        int[] count;
            
                public List<Integer> countSmaller(int[] nums) {
                        int n = nums.length;
                                this.count = new int[n];
                                        int[] indices = new int[n];
                                                
                                                        // Initialize indices to track original positions
                                                                for (int i = 0; i < n; i++) indices[i] = i;
                                                                        
                                                                                mergeSort(nums, indices, 0, n - 1);
                                                                                        
                                                                                                List<Integer> result = new ArrayList<>();
                                                                                                        for (int c : count) result.add(c);
                                                                                                                return result;
                                                                                                                    }
                                                                                                                        
                                                                                                                            private void mergeSort(int[] nums, int[] indices, int left, int right) {
                                                                                                                                    if (left >= right) return;
                                                                                                                                            
                                                                                                                                                    int mid = left + (right - left) / 2;
                                                                                                                                                            mergeSort(nums, indices, left, mid);
                                                                                                                                                                    mergeSort(nums, indices, mid + 1, right);
                                                                                                                                                                            
                                                                                                                                                                                    merge(nums, indices, left, mid, right);
                                                                                                                                                                                        }
                                                                                                                                                                                            
                                                                                                                                                                                                private void merge(int[] nums, int[] indices, int left, int mid, int right) {
                                                                                                                                                                                                        int[] temp = new int[right - left + 1];
                                                                                                                                                                                                                int i = left;      // Pointer for left half
                                                                                                                                                                                                                        int j = mid + 1;   // Pointer for right half
                                                                                                                                                                                                                                int k = 0;
                                                                                                                                                                                                                                        int rightCount = 0; // Tracks how many elements from right side are smaller
                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                        while (i <= mid && j <= right) {
                                                                                                                                                                                                                                                                    if (nums[indices[j]] < nums[indices[i]]) {
                                                                                                                                                                                                                                                                                    // Element on right is smaller
                                                                                                                                                                                                                                                                                                    rightCount++;
                                                                                                                                                                                                                                                                                                                    temp[k++] = indices[j++];
                                                                                                                                                                                                                                                                                                                                } else {
                                                                                                                                                                                                                                                                                                                                                // Element on left is smaller or equal
                                                                                                                                                                                                                                                                                                                                                                // Add the current rightCount to this left element's total
                                                                                                                                                                                                                                                                                                                                                                                count[indices[i]] += rightCount;
                                                                                                                                                                                                                                                                                                                                                                                                temp[k++] = indices[i++];
                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                    // Clean up remaining left elements
                                                                                                                                                                                                                                                                                                                                                                                                                                            while (i <= mid) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                        count[indices[i]] += rightCount;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    temp[k++] = indices[i++];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // Clean up remaining right elements
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    while (j <= right) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                temp[k++] = indices[j++];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // Copy merged result back to indices array
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                System.arraycopy(temp, 0, indices, left, temp.length);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
